//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.MedioClinic;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(CompanyServices.CLASS_NAME, typeof(CompanyServices))]

namespace CMS.DocumentEngine.Types.MedioClinic
{
	/// <summary>
	/// Represents a content item of type CompanyServices.
	/// </summary>
	public partial class CompanyServices : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MedioClinic.CompanyServices";


		/// <summary>
		/// The instance of the class that provides extended API for working with CompanyServices fields.
		/// </summary>
		private readonly CompanyServicesFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CompanyServicesID.
		/// </summary>
		[DatabaseIDField]
		public int CompanyServicesID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CompanyServicesID"), 0);
			}
			set
			{
				SetValue("CompanyServicesID", value);
			}
		}


		/// <summary>
		/// Header.
		/// </summary>
		[DatabaseField]
		public string Header
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Header"), @"");
			}
			set
			{
				SetValue("Header", value);
			}
		}


		/// <summary>
		/// Icon.
		/// </summary>
		[DatabaseField]
		public Guid Icon1
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Icon"), Guid.Empty);
			}
			set
			{
				SetValue("Icon", value);
			}
		}


		/// <summary>
		/// Text.
		/// </summary>
		[DatabaseField]
		public string Text
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Text"), @"");
			}
			set
			{
				SetValue("Text", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CompanyServices fields.
		/// </summary>
		[RegisterProperty]
		public CompanyServicesFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CompanyServices fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CompanyServicesFields : AbstractHierarchicalObject<CompanyServicesFields>
		{
			/// <summary>
			/// The content item of type CompanyServices that is a target of the extended API.
			/// </summary>
			private readonly CompanyServices mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CompanyServicesFields" /> class with the specified content item of type CompanyServices.
			/// </summary>
			/// <param name="instance">The content item of type CompanyServices that is a target of the extended API.</param>
			public CompanyServicesFields(CompanyServices instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CompanyServicesID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CompanyServicesID;
				}
				set
				{
					mInstance.CompanyServicesID = value;
				}
			}


			/// <summary>
			/// Header.
			/// </summary>
			public string Header
			{
				get
				{
					return mInstance.Header;
				}
				set
				{
					mInstance.Header = value;
				}
			}


			/// <summary>
			/// Icon.
			/// </summary>
			public DocumentAttachment Icon
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("Icon");
				}
			}


			/// <summary>
			/// Text.
			/// </summary>
			public string Text
			{
				get
				{
					return mInstance.Text;
				}
				set
				{
					mInstance.Text = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CompanyServices" /> class.
		/// </summary>
		public CompanyServices() : base(CLASS_NAME)
		{
			mFields = new CompanyServicesFields(this);
		}

		#endregion
	}
}